name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "10", "8"]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v2.2.1
        env:
          CC_TEST_REPORTER_ID: 22bd54904a2b6d24a8633419c02bc0cda72e442d328bb0a9d6a44d523e17b151
        with:
          coverageCommand: yarn coverage
